name: test-application-workflow

on:
  pull_request:
    branches:
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['1.15', '1.20']

    steps:
      - uses: actions/checkout@v2 # download from the repo into this ubuntu machine
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: go test
      - run: go run math.go
